version: '3.8'

services:
  api:
    build:
      context: ./api-java
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - QUARKUS_HTTP_PORT=3001
      - JAVA_OPTS=--enable-preview -XX:+UnlockExperimentalVMOptions -XX:+EnableVectorSupport -XX:+UseZGC -XX:+ZGenerational -Xms64m -Xmx256m -XX:MaxRAMPercentage=80.0 -XX:MinRAMPercentage=50.0 -Dfile.encoding=UTF-8 -Djava.awt.headless=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/karate/versions"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      api:
        condition: service_healthy
