quarkus:
  http:
    port: 3001
    cors:
      ~: true
      origins: ${CORS_ORIGINS:http://localhost:3000,https://kaas.netlify.app}
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: Content-Type,Authorization
      exposed-headers: Content-Disposition
      access-control-max-age: 24H
  log:
    category:
      "com.kaas":
        level: DEBUG
  native:
    resources:
      includes: karate-config.js
